workflows:
  android-workflow:
    name: Android Workflow 
    instance_type: mac_mini_m1
    max_build_duration: 20
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '!(*-rc.*)'
          include: true
        - pattern: excluded-tag
          include: false
        - pattern: included-tag
          include: true
    environment:
      flutter:
        version: fvm
    scripts:
      - name: Get APPVERSION
        script: |
          APP_VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          echo $APP_VERSION
