workflows:
  android-workflow:
    name: Android Workflow 
    instance_type: mac_mini_m1
    max_build_duration: 20
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '!(*-rc.*)'
          include: true
        - pattern: excluded-tag
          include: false
        - pattern: included-tag
          include: true
    environment:
      flutter:
        version: fvm
    scripts:
      - name: Show PROJECT_BUILD_NUMBER
        script: |
          echo $PROJECT_BUILD_NUMBER
      - name: Show FLUTTER_BUILD_NAME
        script: |
          echo $FLUTTER_BUILD_NAME
      - name: Show FLUTTER_BUILD_NUMBER
        script: |
          echo $FLUTTER_BUILD_NUMBER
