workflows:
  android-workflow:
    name: Android Workflow 
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      flutter:
        version: fvm
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Flutter unit tests
        script: |
          flutter test
